name: food_delivery
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  bloc: ^8.1.2
  bordered_text: ^2.0.0
  cloud_firestore: ^4.8.1
  contained_tab_bar_view: ^0.8.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  data_connection_checker: ^0.3.4
  equatable: ^2.0.5
  file_picker: ^5.3.1
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.2
  get_it: ^7.6.0
  go_router: ^6.5.6
  google_sign_in: ^6.1.4
  smooth_page_indicator: ^1.0.0+2
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/avatar/
    - assets/welcome/svg/
    - assets/splash/png/
    - assets/onboarding/png/
    - assets/auth/

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Regular.ttf
          weight: 100
        - asset: assets/font/Metropolis-Medium.ttf
          weight: 500
        - asset: assets/font/Metropolis-Bold.ttf
          weight: 700
        - asset: assets/font/Metropolis-Black.ttf
          weight: 900
    - family: Nunito
      fonts:
        - asset: assets/font/Nunito-Regular.ttf
          weight: 100
        - asset: assets/font/Nunito-Medium.ttf
          weight: 500
        - asset: assets/font/Nunito-Bold.ttf
          weight: 700
        - asset: assets/font/Nunito-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 100
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-Black.ttf
          weight: 900
    - family: Gilroy-Bold
      fonts:
        - asset: assets/font/Gilroy-Regular.ttf
          weight: 100
        - asset: assets/font/Gilroy-Medium.ttf
          weight: 400
        - asset: assets/font/Gilroy-Bold.ttf
          weight: 700
