// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFvP7V4de1kG_8m7MKHS0II6cEt6hCYbk',
    appId: '1:323500625721:web:44e0eb4d5ca370a31462e8',
    messagingSenderId: '323500625721',
    projectId: 'fooddelivery-85122',
    authDomain: 'fooddelivery-85122.firebaseapp.com',
    storageBucket: 'fooddelivery-85122.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ6g9VpLXxJbsTT9bXmqwi3Xl1B_zPKd4',
    appId: '1:323500625721:android:8775e860683496fa1462e8',
    messagingSenderId: '323500625721',
    projectId: 'fooddelivery-85122',
    storageBucket: 'fooddelivery-85122.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlkIcAj1L8MEjbgKc8uhmbbl_zqUeItQU',
    appId: '1:323500625721:ios:3cba1660d5aca4dd1462e8',
    messagingSenderId: '323500625721',
    projectId: 'fooddelivery-85122',
    storageBucket: 'fooddelivery-85122.appspot.com',
    iosClientId: '323500625721-9ie0ilrfhjja1a5suo0icdcof1kd0eg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlkIcAj1L8MEjbgKc8uhmbbl_zqUeItQU',
    appId: '1:323500625721:ios:3cba1660d5aca4dd1462e8',
    messagingSenderId: '323500625721',
    projectId: 'fooddelivery-85122',
    storageBucket: 'fooddelivery-85122.appspot.com',
    iosClientId: '323500625721-9ie0ilrfhjja1a5suo0icdcof1kd0eg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDivery',
  );
}
